export const AUTHENTICATION_TITLE = 'Authentication';
export const AUTHENTICATION_LOGIN_REQUEST = 'AUTHENTICATION_LOGIN_REQUEST';
export const AUTHENTICATION_REGISTER_REQUEST = 'AUTHENTICATION_REGISTER_REQUEST';
export const AUTHENTICATION_GET_USER_PROFILE_REQUEST = 'AUTHENTICATION_GET_USER_PROFILE_REQUEST';
